sudo: required
services: 
        - docker

before_install:
        - docker build -t  MidnightOwl73/docker-react -f Dockerfile.dev .

script:
        - docker run MidnightOwl73/docker-react npm run test -- --coverage